#!usr/bin/env python3

import sys
from igpay import *

if __name__ == '__main__':
    #gets the input file from command line
    with open(sys.argv[1], "r") as inputFile:

        for lines in inputFile:
            #delimit the line based on spaces
            lines = lines.split()

            #check each word and sent to igpay
            for word in lines:
                #check for non letter characters.
                if word[-1].isalpha():
                    print(igpay(word), end = " ")


                else:
                    print(igpay(word[:-1]) + word[-1], end=" ")

            print(" ")
